image: bioconductor/bioconductor_docker:RELEASE_3_13

before_script:
  - source tools/ci_r_setup.bash

test:
  script:
    # Install devscripts for for devtools::check() to inspect configure:
    # https://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT26 We.
    # also need libtool for automake, and doxygen for checking C docstrings.
    - apt -qqq update
    - apt -qqq install devscripts libtool doxygen
    # The usual.
    - autoreconf --verbose --install --force --warnings=all
    - Rscript -e 'system.time(devtools::install(dependencies = TRUE, quiet = TRUE))'
    - Rscript -e 'devtools::check(vignettes = FALSE, error_on = "error")'
    # Warn if any C code is undocumented.
    - ./configure # Create src/Doxyfile from src/Doxyfile.in
    - pushd src/
    - doxygen
  cache:
    paths:
      - library/
    policy: pull-push
