image: bioconductor/bioconductor_docker:RELEASE_3_10

before_script:
  - export R_LIBS_USER=$PWD/library
  - export R_PROFILE_USER=$PWD/.Rprofile
  - mkdir -vp $R_LIBS_USER
  - |
    cat <<EOF > $R_PROFILE_USER
    local({
        .libPaths("$R_LIBS_USER")
        options(repos = BiocManager::repositories())
    })
    EOF

test:
  script:
    - Rscript -e 'system.time(devtools::install(dependencies = TRUE, quiet = TRUE))'
    - Rscript -e 'devtools::check()'
  cache:
    paths:
      - library/
    policy: pull-push
