image: bioconductor/bioconductor_docker:RELEASE_3_13

before_script:
  - source tools/ci_r_setup.bash

test:
  script:
    # Install devscripts for for devtools::check() to inspect configure:
    # https://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT26
    - apt -qqq update
    - apt -qqq install devscripts
    # The usual.
    - Rscript -e 'system.time(devtools::install(dependencies = TRUE, quiet = TRUE))'
    - Rscript -e 'devtools::check(vignettes = FALSE)'
  cache:
    paths:
      - library/
    policy: pull-push
