image: bioconductor/bioconductor_docker:RELEASE_3_13

before_script:
  - source tools/ci_r_setup.bash

test:
  script:
    # The usual.
    - Rscript -e 'system.time(devtools::install(dependencies = TRUE, quiet = TRUE))'
    - Rscript -e 'devtools::check(vignettes = FALSE, error_on = "error")'
    # Warn if any C code is undocumented.
    - ./configure # Create src/Doxyfile from src/Doxyfile.in
    - pushd src/
    - apt -qqq update
    - apt -qqq install doxygen
    - doxygen
  cache:
    paths:
      - library/
    policy: pull-push
