image: bioconductor/bioconductor_docker:RELEASE_3_11

before_script:
  - source tools/ci_r_setup.bash

test:
  script:
    - Rscript -e 'system.time(devtools::install(dependencies = TRUE, quiet = TRUE))'
    - Rscript -e 'devtools::check(vignettes = FALSE)'
  cache:
    paths:
      - library/
    policy: pull-push
