## Hidden states.
B <- 0L
N1 <- 1L; N2 <- 2L; N3 <- 3L
P1 <- 4L; P2 <- 5L; P3 <- 6L
## Untrained model.
states <- c("B", "N1", "N2", "N3", "P1", "P2", "P3")
emissions <- c("no signal", "enriched", "depleted")
model <- list(
    trans = matrix(c(
        0.99, 0.005, 0.0, 0.0, 0.005, 0.0, 0.00,
        0.00, 0.000, 1.0, 0.0, 0.000, 0.0, 0.00,
        0.00, 0.000, 0.5, 0.5, 0.000, 0.0, 0.00,
        1.00, 0.000, 0.0, 0.0, 0.000, 0.0, 0.00,
        0.00, 0.000, 0.0, 0.0, 0.500, 0.5, 0.00,
        0.00, 0.000, 0.0, 0.0, 0.450, 0.1, 0.45,
        0.50, 0.000, 0.0, 0.0, 0.000, 0.0, 0.50),
        ncol = 7, byrow = TRUE,
        dimnames = list(states, states)),
    emis = matrix(c(
        0.90, 0.05, 0.05,
        0.09, 0.90, 0.01,
        0.09, 0.90, 0.01,
        0.09, 0.90, 0.01,
        0.10, 0.45, 0.45,
        0.10, 0.45, 0.45,
        0.10, 0.45, 0.45),
        ncol = 3, byrow = TRUE,
        dimnames = list(states, emissions)))

test_that("viterbi decodes enhancer region", {
    ## These observations are from ENCODE enhancer ID EH37E0477524 + strand.  See
    ## section 2.2.5 of https://coregenomics.gitlab.io/evolength/ generated by
    ## git commit 24df359 of https://gitlab.com/coregenomics/evolength
    len <- 92
    observations <- rep.int(0L, len)
    observations[c(19, 22, 26, 27, 28, 29, 30, 31, 36, 54, 55, 56,
                   57, 58, 59, 61, 63, 71, 78, 79, 80, 81, 82, 84) + 1] <- 2L
    ## These hidden states were calculated from the RcppHMM mentioned in the
    ## observations URLs and git commit ID above.
    expected_states <-
        c(B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, P1, P1, P1, P1,
          P2, P3, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, P1, P1, P1, P1, P2, P3,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, P1, P1,
          P1, P2, P3, B, B, B, B, B, B, B,
          B, B)
    hidden_states <- viterbi(observations)
    expect_equal(hidden_states, expected_states)
})

test_that("viterbi has a vectorized implementation", {
    ## Simulate data from the HMM.
    set.seed(99)
    states_list <- IntegerList()
    obs_list <- IntegerList()
    for (li in seq(1, 10)) {
        ## Generate the initial hidden value.
        latent <- sample(c("N1", "P1"), 1, prob = c(0.5, 0.5))
        ## Generate the corresponding observation.
        states_1k <- vector("integer", 1000L)
        obs_1k <- vector("integer", 1000L)
        states_1k[1] <- match(latent, states) -1
        obs_1k[1] <- sample(seq_along(emissions) - 1, size = 1,
                            prob = model$emis[latent, ])
        ## Generate the subsequent hidden value and corresponding observations.
        for (i in seq_along(obs_1k)[-1]) {
            latent <-    sample(states, size = 1,
                                prob = model$trans[latent, ])
            obs_1k[i] <- sample(seq_along(emissions) - 1, size = 1,
                                prob = model$emis[latent, ])
            states_1k[i] <- match(latent, states) -1
        }
        states_list[[li]] <- states_1k
        obs_list[[li]] <- obs_1k
    }
    states_decoded <- viterbi(obs_list)
})
