test_that("viterbi decodes enhancer region", {
    ## These observations are from ENCODE enhancer ID EH37E0477524 + strand.  See
    ## section 2.2.5 of https://coregenomics.gitlab.io/evolength/ generated by
    ## git commit 24df359 of https://gitlab.com/coregenomics/evolength
    len <- 92
    observations <- rep.int(0L, len)
    observations[c(19, 22, 26, 27, 28, 29, 30, 31, 36, 54, 55, 56,
                   57, 58, 59, 61, 63, 71, 78, 79, 80, 81, 82, 84) + 1] <- 2L
    ## These hidden states were calculated from the RcppHMM mentioned in the
    ## observations URLs and git commit ID above.
    B <- 0L
    N1 <- 1L; N2 <- 2L; N3 <- 3L
    P1 <- 4L; P2 <- 5L; P3 <- 6L
    expected_states <-
        c(B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, P1, P1, P1, P1,
          P2, P3, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, P1, P1, P1, P1, P2, P3,
          B, B, B, B, B, B, B, B, B, B,
          B, B, B, B, B, B, B, B, P1, P1,
          P1, P2, P3, B, B, B, B, B, B, B,
          B, B)
    hidden_states <- viterbi(observations)
    expect_equal(hidden_states, expected_states)
})
